/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcustEntityInfoEntities {
    #[serde(rename = "canTrade", skip_serializing_if = "Option::is_none")]
    pub can_trade: Option<bool>,
    #[serde(rename = "canSign", skip_serializing_if = "Option::is_none")]
    pub can_sign: Option<bool>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<crate::models::IbcustEntityInfoName>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<crate::models::IbcustEntityInfoAddress>,
    #[serde(rename = "identDocs", skip_serializing_if = "Option::is_none")]
    pub ident_docs: Option<Vec<serde_json::Value>>,
}

impl IbcustEntityInfoEntities {
    pub fn new() -> IbcustEntityInfoEntities {
        IbcustEntityInfoEntities {
            can_trade: None,
            can_sign: None,
            _type: None,
            name: None,
            address: None,
            ident_docs: None,
        }
    }
}


