/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverSecdefSearchSections {
    /// Asset Class
    #[serde(rename = "secType", skip_serializing_if = "Option::is_none")]
    pub sec_type: Option<String>,
    /// List of expiration month(s) and year(s) in MMMYY format separated by semicolon
    #[serde(rename = "months", skip_serializing_if = "Option::is_none")]
    pub months: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Listing Exchange
    #[serde(rename = "exchange", skip_serializing_if = "Option::is_none")]
    pub exchange: Option<String>,
    /// For combo's defines the asset class for each leg
    #[serde(rename = "legSecType", skip_serializing_if = "Option::is_none")]
    pub leg_sec_type: Option<String>,
}

impl IserverSecdefSearchSections {
    pub fn new() -> IserverSecdefSearchSections {
        IserverSecdefSearchSections {
            sec_type: None,
            months: None,
            symbol: None,
            exchange: None,
            leg_sec_type: None,
        }
    }
}


