/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Account : account information



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Account {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "accountVan", skip_serializing_if = "Option::is_none")]
    pub account_van: Option<String>,
    #[serde(rename = "accountTitle", skip_serializing_if = "Option::is_none")]
    pub account_title: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "accountAlias", skip_serializing_if = "Option::is_none")]
    pub account_alias: Option<String>,
    #[serde(rename = "accountStatus", skip_serializing_if = "Option::is_none")]
    pub account_status: Option<f32>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "tradingType", skip_serializing_if = "Option::is_none")]
    pub trading_type: Option<String>,
    #[serde(rename = "faclient", skip_serializing_if = "Option::is_none")]
    pub faclient: Option<bool>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    #[serde(rename = "desc", skip_serializing_if = "Option::is_none")]
    pub desc: Option<String>,
    #[serde(rename = "covestor", skip_serializing_if = "Option::is_none")]
    pub covestor: Option<bool>,
    #[serde(rename = "master", skip_serializing_if = "Option::is_none")]
    pub master: Option<crate::models::AccountMaster>,
}

impl Account {
    /// account information
    pub fn new() -> Account {
        Account {
            id: None,
            account_id: None,
            account_van: None,
            account_title: None,
            display_name: None,
            account_alias: None,
            account_status: None,
            currency: None,
            _type: None,
            trading_type: None,
            faclient: None,
            parent: None,
            desc: None,
            covestor: None,
            master: None,
        }
    }
}


