/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarRequest {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<crate::models::CalendarRequestDate>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<crate::models::CalendarRequestFilters>,
}

impl CalendarRequest {
    pub fn new() -> CalendarRequest {
        CalendarRequest {
            date: None,
            filters: None,
        }
    }
}


