/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalendarRequestFilters {
    /// value can be 'true' or 'false'.
    #[serde(rename = "recently_held", skip_serializing_if = "Option::is_none")]
    pub recently_held: Option<String>,
    /// value can be 'true' or 'false'.
    #[serde(rename = "corporate_earnings", skip_serializing_if = "Option::is_none")]
    pub corporate_earnings: Option<String>,
    /// value can be 'true' or 'false'.
    #[serde(rename = "DivExDates", skip_serializing_if = "Option::is_none")]
    pub div_ex_dates: Option<String>,
    /// value can be 'true' or 'false'.
    #[serde(rename = "ipo", skip_serializing_if = "Option::is_none")]
    pub ipo: Option<String>,
    /// value can be 'true' or 'false'.
    #[serde(rename = "splits", skip_serializing_if = "Option::is_none")]
    pub splits: Option<String>,
    /// value can be 'true' or 'false'.
    #[serde(rename = "corporate_events", skip_serializing_if = "Option::is_none")]
    pub corporate_events: Option<String>,
    /// value can be 'true' or 'false'.
    #[serde(rename = "economic_events", skip_serializing_if = "Option::is_none")]
    pub economic_events: Option<String>,
    /// value can be 'true' or 'false'.
    #[serde(rename = "option_show_monthly", skip_serializing_if = "Option::is_none")]
    pub option_show_monthly: Option<String>,
    /// value can be 'true' or 'false'.
    #[serde(rename = "option_show_weekly", skip_serializing_if = "Option::is_none")]
    pub option_show_weekly: Option<String>,
    /// default is 'All'.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// default is '250'.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    /// default is '50'.
    #[serde(rename = "limit_region", skip_serializing_if = "Option::is_none")]
    pub limit_region: Option<String>,
}

impl CalendarRequestFilters {
    pub fn new() -> CalendarRequestFilters {
        CalendarRequestFilters {
            recently_held: None,
            corporate_earnings: None,
            div_ex_dates: None,
            ipo: None,
            splits: None,
            corporate_events: None,
            economic_events: None,
            option_show_monthly: None,
            option_show_weekly: None,
            country: None,
            limit: None,
            limit_region: None,
        }
    }
}


