/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2003 {
    /// disclaimer message
    #[serde(rename = "DT", skip_serializing_if = "Option::is_none")]
    pub DT: Option<String>,
    /// fyi code
    #[serde(rename = "FC", skip_serializing_if = "Option::is_none")]
    pub FC: Option<String>,
}

impl InlineResponse2003 {
    pub fn new() -> InlineResponse2003 {
        InlineResponse2003 {
            DT: None,
            FC: None,
        }
    }
}


