/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20023 {
    #[serde(rename = "scan_type_list", skip_serializing_if = "Option::is_none")]
    pub scan_type_list: Option<Vec<crate::models::InlineResponse20023ScanTypeList>>,
    #[serde(rename = "instrument_list", skip_serializing_if = "Option::is_none")]
    pub instrument_list: Option<Vec<crate::models::InlineResponse20023InstrumentList>>,
    #[serde(rename = "filter_list", skip_serializing_if = "Option::is_none")]
    pub filter_list: Option<Vec<crate::models::InlineResponse20023FilterList>>,
    #[serde(rename = "location_tree", skip_serializing_if = "Option::is_none")]
    pub location_tree: Option<Vec<crate::models::InlineResponse20023LocationTree>>,
}

impl InlineResponse20023 {
    pub fn new() -> InlineResponse20023 {
        InlineResponse20023 {
            scan_type_list: None,
            instrument_list: None,
            filter_list: None,
            location_tree: None,
        }
    }
}


