/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20033 {
    #[serde(rename = "applicantId", skip_serializing_if = "Option::is_none")]
    pub applicant_id: Option<f32>,
    #[serde(rename = "entities", skip_serializing_if = "Option::is_none")]
    pub entities: Option<Vec<crate::models::IbcustEntityInfoEntities>>,
}

impl InlineResponse20033 {
    pub fn new() -> InlineResponse20033 {
        InlineResponse20033 {
            applicant_id: None,
            entities: None,
        }
    }
}


