/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse2005E : device



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2005E {
    /// device name
    #[serde(rename = "NM", skip_serializing_if = "Option::is_none")]
    pub NM: Option<String>,
    /// device id
    #[serde(rename = "I", skip_serializing_if = "Option::is_none")]
    pub I: Option<String>,
    /// unique device id
    #[serde(rename = "UI", skip_serializing_if = "Option::is_none")]
    pub UI: Option<String>,
    /// device is enabled or not 0-true, 1-false.
    #[serde(rename = "A", skip_serializing_if = "Option::is_none")]
    pub A: Option<String>,
}

impl InlineResponse2005E {
    /// device
    pub fn new() -> InlineResponse2005E {
        InlineResponse2005E {
            NM: None,
            I: None,
            UI: None,
            A: None,
        }
    }
}


