/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20011Orders {
    /// Account number
    #[serde(rename = "acct", skip_serializing_if = "Option::is_none")]
    pub acct: Option<String>,
    /// Exchange or trading venue
    #[serde(rename = "exchange", skip_serializing_if = "Option::is_none")]
    pub exchange: Option<String>,
    /// Contract identifier
    #[serde(rename = "conid", skip_serializing_if = "Option::is_none")]
    pub conid: Option<f32>,
    /// Order identifier
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    /// Cash currency
    #[serde(rename = "cashCcy", skip_serializing_if = "Option::is_none")]
    pub cash_ccy: Option<String>,
    /// Quantity outstanding and total quantity concatenated with forward slash separator
    #[serde(rename = "sizeAndFills", skip_serializing_if = "Option::is_none")]
    pub size_and_fills: Option<f32>,
    /// Order description
    #[serde(rename = "orderDesc", skip_serializing_if = "Option::is_none")]
    pub order_desc: Option<String>,
    /// Formatted ticker description
    #[serde(rename = "description1", skip_serializing_if = "Option::is_none")]
    pub description1: Option<String>,
    /// Underlying symbol
    #[serde(rename = "ticker", skip_serializing_if = "Option::is_none")]
    pub ticker: Option<String>,
    /// Asset class
    #[serde(rename = "secType", skip_serializing_if = "Option::is_none")]
    pub sec_type: Option<String>,
    /// Listing Exchange
    #[serde(rename = "listingExchange", skip_serializing_if = "Option::is_none")]
    pub listing_exchange: Option<String>,
    /// Quantity remaining
    #[serde(rename = "remainingQuantity", skip_serializing_if = "Option::is_none")]
    pub remaining_quantity: Option<f32>,
    /// Quantity filled
    #[serde(rename = "filledQuantity", skip_serializing_if = "Option::is_none")]
    pub filled_quantity: Option<f32>,
    /// Company Name
    #[serde(rename = "companyName", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    /// Status of the order
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Original order type
    #[serde(rename = "origOrderType", skip_serializing_if = "Option::is_none")]
    pub orig_order_type: Option<String>,
    /// Supports Tax Optimization with 0 for no and 1 for yes
    #[serde(rename = "supportsTaxOpt", skip_serializing_if = "Option::is_none")]
    pub supports_tax_opt: Option<f32>,
    /// Last status update in format YYMMDDhhmms based in GMT
    #[serde(rename = "lastExecutionTime", skip_serializing_if = "Option::is_none")]
    pub last_execution_time: Option<f32>,
    /// Last status update unix time in ms
    #[serde(rename = "lastExecutionTime_r", skip_serializing_if = "Option::is_none")]
    pub last_execution_time_r: Option<f32>,
    /// Order type
    #[serde(rename = "orderType", skip_serializing_if = "Option::is_none")]
    pub order_type: Option<String>,
    /// Order reference
    #[serde(rename = "order_ref", skip_serializing_if = "Option::is_none")]
    pub order_ref: Option<String>,
    /// Side of order
    #[serde(rename = "side", skip_serializing_if = "Option::is_none")]
    pub side: Option<String>,
    /// Time in force
    #[serde(rename = "timeInForce", skip_serializing_if = "Option::is_none")]
    pub time_in_force: Option<String>,
    /// Price of order
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f32>,
    /// background color in hex format
    #[serde(rename = "bgColor", skip_serializing_if = "Option::is_none")]
    pub bg_color: Option<String>,
    /// foreground color in hex format
    #[serde(rename = "fgColor", skip_serializing_if = "Option::is_none")]
    pub fg_color: Option<String>,
}

impl InlineResponse20011Orders {
    pub fn new() -> InlineResponse20011Orders {
        InlineResponse20011Orders {
            acct: None,
            exchange: None,
            conid: None,
            order_id: None,
            cash_ccy: None,
            size_and_fills: None,
            order_desc: None,
            description1: None,
            ticker: None,
            sec_type: None,
            listing_exchange: None,
            remaining_quantity: None,
            filled_quantity: None,
            company_name: None,
            status: None,
            orig_order_type: None,
            supports_tax_opt: None,
            last_execution_time: None,
            last_execution_time_r: None,
            order_type: None,
            order_ref: None,
            side: None,
            time_in_force: None,
            price: None,
            bg_color: None,
            fg_color: None,
        }
    }
}


