/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20021 {
    #[serde(rename = "call", skip_serializing_if = "Option::is_none")]
    pub call: Option<Vec<String>>,
    #[serde(rename = "put", skip_serializing_if = "Option::is_none")]
    pub put: Option<Vec<String>>,
}

impl InlineResponse20021 {
    pub fn new() -> InlineResponse20021 {
        InlineResponse20021 {
            call: None,
            put: None,
        }
    }
}


