/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20022String {
    /// Outside of Regular Trading Hours
    #[serde(rename = "ORTH", skip_serializing_if = "Option::is_none")]
    pub ORTH: Option<bool>,
    /// Stop Price value
    #[serde(rename = "SP", skip_serializing_if = "Option::is_none")]
    pub SP: Option<String>,
    /// Limit Price value
    #[serde(rename = "LP", skip_serializing_if = "Option::is_none")]
    pub LP: Option<String>,
    /// Price Cap value
    #[serde(rename = "PC", skip_serializing_if = "Option::is_none")]
    pub PC: Option<String>,
    /// Trailing amount value
    #[serde(rename = "TA", skip_serializing_if = "Option::is_none")]
    pub TA: Option<String>,
    /// Trailing unit
    #[serde(rename = "TU", skip_serializing_if = "Option::is_none")]
    pub TU: Option<String>,
    /// Releative offset amount
    #[serde(rename = "ROA", skip_serializing_if = "Option::is_none")]
    pub ROA: Option<String>,
    /// Relative offset percent
    #[serde(rename = "ROP", skip_serializing_if = "Option::is_none")]
    pub ROP: Option<String>,
    /// Touch trigger price
    #[serde(rename = "TT", skip_serializing_if = "Option::is_none")]
    pub TT: Option<String>,
    /// Use Net Price for Bonds
    #[serde(rename = "UNP", skip_serializing_if = "Option::is_none")]
    pub UNP: Option<bool>,
}

impl InlineResponse20022String {
    pub fn new() -> InlineResponse20022String {
        InlineResponse20022String {
            ORTH: None,
            SP: None,
            LP: None,
            PC: None,
            TA: None,
            TU: None,
            ROA: None,
            ROP: None,
            TT: None,
            UNP: None,
        }
    }
}


