/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject11 {
    #[serde(rename = "acctIds", skip_serializing_if = "Option::is_none")]
    pub acct_ids: Option<Vec<String>>,
    #[serde(rename = "conids", skip_serializing_if = "Option::is_none")]
    pub conids: Option<Vec<f32>>,
    /// optional defaults to USD.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// optional, default value is 90
    #[serde(rename = "days", skip_serializing_if = "Option::is_none")]
    pub days: Option<f32>,
}

impl InlineObject11 {
    pub fn new() -> InlineObject11 {
        InlineObject11 {
            acct_ids: None,
            conids: None,
            currency: None,
            days: None,
        }
    }
}


