/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20030 {
    #[serde(rename = "BASE", skip_serializing_if = "Option::is_none")]
    pub BASE: Option<crate::models::Ledger>,
}

impl InlineResponse20030 {
    pub fn new() -> InlineResponse20030 {
        InlineResponse20030 {
            BASE: None,
        }
    }
}


