/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20010 {
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<i32>,
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i32>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "order_status", skip_serializing_if = "Option::is_none")]
    pub order_status: Option<String>,
    #[serde(rename = "failure_list", skip_serializing_if = "Option::is_none")]
    pub failure_list: Option<String>,
}

impl InlineResponse20010 {
    pub fn new() -> InlineResponse20010 {
        InlineResponse20010 {
            request_id: None,
            order_id: None,
            success: None,
            text: None,
            order_status: None,
            failure_list: None,
        }
    }
}


