/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2009 {
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i32>,
    /// account id
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
    #[serde(rename = "alert_name", skip_serializing_if = "Option::is_none")]
    pub alert_name: Option<String>,
    /// Value can only be 0 or 1, 1 means active
    #[serde(rename = "alert_active", skip_serializing_if = "Option::is_none")]
    pub alert_active: Option<i32>,
    /// format, YYYYMMDD-HH:mm:ss, the time when you created the alert 
    #[serde(rename = "order_time", skip_serializing_if = "Option::is_none")]
    pub order_time: Option<String>,
    /// whether the alert has been triggered or not
    #[serde(rename = "alert_triggered", skip_serializing_if = "Option::is_none")]
    pub alert_triggered: Option<bool>,
    /// whether the alert can be repeatable or not, value can be 1 or 0. 1 means true
    #[serde(rename = "alert_repeatable", skip_serializing_if = "Option::is_none")]
    pub alert_repeatable: Option<i32>,
}

impl InlineResponse2009 {
    pub fn new() -> InlineResponse2009 {
        InlineResponse2009 {
            order_id: None,
            account: None,
            alert_name: None,
            alert_active: None,
            order_time: None,
            alert_triggered: None,
            alert_repeatable: None,
        }
    }
}


