/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20022OrderDefaults {
    /// orderType
    #[serde(rename = "string", skip_serializing_if = "Option::is_none")]
    pub string: Option<Vec<crate::models::InlineResponse20022String>>,
}

impl InlineResponse20022OrderDefaults {
    pub fn new() -> InlineResponse20022OrderDefaults {
        InlineResponse20022OrderDefaults {
            string: None,
        }
    }
}


