/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject2 {
    /// alert id(order id)
    #[serde(rename = "alertId", skip_serializing_if = "Option::is_none")]
    pub alert_id: Option<i32>,
    /// 1 to activate, 0 to deactivate
    #[serde(rename = "alertActive", skip_serializing_if = "Option::is_none")]
    pub alert_active: Option<i32>,
}

impl InlineObject2 {
    pub fn new() -> InlineObject2 {
        InlineObject2 {
            alert_id: None,
            alert_active: None,
        }
    }
}


