/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20012 {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Please note here, if the message is a question, you have to reply to question in order to submit the order successfully. See more in the \"/iserver/reply/{replyid}\" endpoint. 
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<Vec<String>>,
}

impl InlineResponse20012 {
    pub fn new() -> InlineResponse20012 {
        InlineResponse20012 {
            id: None,
            message: None,
        }
    }
}


