/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20020 {
    /// Contract Identifier
    #[serde(rename = "conid", skip_serializing_if = "Option::is_none")]
    pub conid: Option<i32>,
    /// Company Name - Exchange
    #[serde(rename = "companyHeader", skip_serializing_if = "Option::is_none")]
    pub company_header: Option<String>,
    #[serde(rename = "companyName", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Exchange
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "restricted", skip_serializing_if = "Option::is_none")]
    pub restricted: Option<String>,
    #[serde(rename = "fop", skip_serializing_if = "Option::is_none")]
    pub fop: Option<String>,
    #[serde(rename = "opt", skip_serializing_if = "Option::is_none")]
    pub opt: Option<String>,
    #[serde(rename = "war", skip_serializing_if = "Option::is_none")]
    pub war: Option<String>,
    #[serde(rename = "sections", skip_serializing_if = "Option::is_none")]
    pub sections: Option<Vec<crate::models::IserverSecdefSearchSections>>,
}

impl InlineResponse20020 {
    pub fn new() -> InlineResponse20020 {
        InlineResponse20020 {
            conid: None,
            company_header: None,
            company_name: None,
            symbol: None,
            description: None,
            restricted: None,
            fop: None,
            opt: None,
            war: None,
            sections: None,
        }
    }
}


