/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20026 {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// null is returned.
    #[serde(rename = "tradeVenueId", skip_serializing_if = "Option::is_none")]
    pub trade_venue_id: Option<String>,
    /// Always contains at least one 'tradingTime'  and zero or more 'sessionTime' tags
    #[serde(rename = "schedules", skip_serializing_if = "Option::is_none")]
    pub schedules: Option<Vec<crate::models::InlineResponse20026Schedules>>,
}

impl InlineResponse20026 {
    pub fn new() -> InlineResponse20026 {
        InlineResponse20026 {
            id: None,
            trade_venue_id: None,
            schedules: None,
        }
    }
}


