/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2002 {
    /// optional, if A doesn't exist, it means user can't toggle this option. 0-off, 1-on.
    #[serde(rename = "A", skip_serializing_if = "Option::is_none")]
    pub A: Option<i32>,
    /// fyi code
    #[serde(rename = "FC", skip_serializing_if = "Option::is_none")]
    pub FC: Option<String>,
    /// disclaimer read, 1 = yes, = 0 no.
    #[serde(rename = "H", skip_serializing_if = "Option::is_none")]
    pub H: Option<i32>,
    /// detailed description
    #[serde(rename = "FD", skip_serializing_if = "Option::is_none")]
    pub FD: Option<String>,
    /// title
    #[serde(rename = "FN", skip_serializing_if = "Option::is_none")]
    pub FN: Option<String>,
}

impl InlineResponse2002 {
    pub fn new() -> InlineResponse2002 {
        InlineResponse2002 {
            A: None,
            FC: None,
            H: None,
            FD: None,
            FN: None,
        }
    }
}


