/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20019 {
    /// true means market data is canceled, false means it is not.
    #[serde(rename = "confirmed", skip_serializing_if = "Option::is_none")]
    pub confirmed: Option<bool>,
}

impl InlineResponse20019 {
    pub fn new() -> InlineResponse20019 {
        InlineResponse20019 {
            confirmed: None,
        }
    }
}


