/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketData {
    /// IBKR Contract ID
    #[serde(rename = "Conid", skip_serializing_if = "Option::is_none")]
    pub conid: Option<f32>,
    /// Exchange
    #[serde(rename = "Exchange", skip_serializing_if = "Option::is_none")]
    pub exchange: Option<String>,
    #[serde(rename = "minTick", skip_serializing_if = "Option::is_none")]
    pub min_tick: Option<f32>,
    #[serde(rename = "Last", skip_serializing_if = "Option::is_none")]
    pub last: Option<f32>,
    #[serde(rename = "LastSize", skip_serializing_if = "Option::is_none")]
    pub last_size: Option<f32>,
    #[serde(rename = "Bid", skip_serializing_if = "Option::is_none")]
    pub bid: Option<f32>,
    #[serde(rename = "BidSize", skip_serializing_if = "Option::is_none")]
    pub bid_size: Option<f32>,
    #[serde(rename = "Ask", skip_serializing_if = "Option::is_none")]
    pub ask: Option<f32>,
    #[serde(rename = "AskSize", skip_serializing_if = "Option::is_none")]
    pub ask_size: Option<f32>,
}

impl MarketData {
    pub fn new() -> MarketData {
        MarketData {
            conid: None,
            exchange: None,
            min_tick: None,
            last: None,
            last_size: None,
            bid: None,
            bid_size: None,
            ask: None,
            ask_size: None,
        }
    }
}


