/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PerformanceNav : Net asset value data for the account or consolidated accounts. NAV data is not applicable to benchmarks.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerformanceNav {
    /// array of dates, the length should be same as the length of returns inside data.
    #[serde(rename = "dates", skip_serializing_if = "Option::is_none")]
    pub dates: Option<Vec<String>>,
    /// D means Day
    #[serde(rename = "freq", skip_serializing_if = "Option::is_none")]
    pub freq: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::PerformanceCpsData>>,
}

impl PerformanceNav {
    /// Net asset value data for the account or consolidated accounts. NAV data is not applicable to benchmarks.
    pub fn new() -> PerformanceNav {
        PerformanceNav {
            dates: None,
            freq: None,
            data: None,
        }
    }
}


