/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Performance {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "cps", skip_serializing_if = "Option::is_none")]
    pub cps: Option<crate::models::PerformanceCps>,
    #[serde(rename = "tpps", skip_serializing_if = "Option::is_none")]
    pub tpps: Option<crate::models::PerformanceTpps>,
    #[serde(rename = "nav", skip_serializing_if = "Option::is_none")]
    pub nav: Option<crate::models::PerformanceNav>,
    #[serde(rename = "pm", skip_serializing_if = "Option::is_none")]
    pub pm: Option<String>,
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<String>>,
    #[serde(rename = "currencyType", skip_serializing_if = "Option::is_none")]
    pub currency_type: Option<String>,
    #[serde(rename = "rc", skip_serializing_if = "Option::is_none")]
    pub rc: Option<i32>,
}

impl Performance {
    pub fn new() -> Performance {
        Performance {
            id: None,
            cps: None,
            tpps: None,
            nav: None,
            pm: None,
            included: None,
            currency_type: None,
            rc: None,
        }
    }
}


