/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScannerParamsInstrumentListInstrument {
    /// Type of the asset
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// Display name for the instrument
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "shortName", skip_serializing_if = "Option::is_none")]
    pub short_name: Option<String>,
    /// Sec Type of the instrument. This field is not provided if its value is same as 'type'
    #[serde(rename = "secType", skip_serializing_if = "Option::is_none")]
    pub sec_type: Option<String>,
    /// Supported filters for the instrument separated by a comma
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<String>,
}

impl ScannerParamsInstrumentListInstrument {
    pub fn new() -> ScannerParamsInstrumentListInstrument {
        ScannerParamsInstrumentListInstrument {
            _type: None,
            name: None,
            short_name: None,
            sec_type: None,
            filters: None,
        }
    }
}


