/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScannerParamsScanTypeListScanType {
    /// Instrument types separated by a comma which are supported for this scan type
    #[serde(rename = "instruments", skip_serializing_if = "Option::is_none")]
    pub instruments: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// scan code which ahs to be provided while querying scanner with this scan type
    #[serde(rename = "scanCode", skip_serializing_if = "Option::is_none")]
    pub scan_code: Option<String>,
}

impl ScannerParamsScanTypeListScanType {
    pub fn new() -> ScannerParamsScanTypeListScanType {
        ScannerParamsScanTypeListScanType {
            instruments: None,
            display_name: None,
            scan_code: None,
        }
    }
}


