/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScannerParamsScanTypeList : Contains list of scan types for which scanner can be ran



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScannerParamsScanTypeList {
    #[serde(rename = "ScanType", skip_serializing_if = "Option::is_none")]
    pub scan_type: Option<Vec<crate::models::ScannerParamsScanTypeListScanType>>,
}

impl ScannerParamsScanTypeList {
    /// Contains list of scan types for which scanner can be ran
    pub fn new() -> ScannerParamsScanTypeList {
        ScannerParamsScanTypeList {
            scan_type: None,
        }
    }
}


