/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScannerParamsLocationTreeLocation {
    #[serde(rename = "instruments", skip_serializing_if = "Option::is_none")]
    pub instruments: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "locationCode", skip_serializing_if = "Option::is_none")]
    pub location_code: Option<String>,
    #[serde(rename = "routeExchange", skip_serializing_if = "Option::is_none")]
    pub route_exchange: Option<String>,
}

impl ScannerParamsLocationTreeLocation {
    pub fn new() -> ScannerParamsLocationTreeLocation {
        ScannerParamsLocationTreeLocation {
            instruments: None,
            display_name: None,
            location_code: None,
            route_exchange: None,
        }
    }
}


