/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScannerParams {
    #[serde(rename = "InstrumentList", skip_serializing_if = "Option::is_none")]
    pub instrument_list: Option<crate::models::ScannerParamsInstrumentList>,
    #[serde(rename = "LocationTree", skip_serializing_if = "Option::is_none")]
    pub location_tree: Option<crate::models::ScannerParamsLocationTree>,
    /// Contains list of filters supported for the scanner
    #[serde(rename = "FilterList", skip_serializing_if = "Option::is_none")]
    pub filter_list: Option<Vec<serde_json::Value>>,
    #[serde(rename = "ScanTypeList", skip_serializing_if = "Option::is_none")]
    pub scan_type_list: Option<crate::models::ScannerParamsScanTypeList>,
}

impl ScannerParams {
    pub fn new() -> ScannerParams {
        ScannerParams {
            instrument_list: None,
            location_tree: None,
            filter_list: None,
            scan_type_list: None,
        }
    }
}


