/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ScannerParamsLocationTree : Contains list of instruments for which scanner can be ran



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScannerParamsLocationTree {
    /// Contains information like name, supported filters, etc. for an instrument. A location can contain more locations forming a tree-like structure which allows user to control the lcoation at more granular level. locationCode has to be used to specify lcoations while querying a scanner.
    #[serde(rename = "Location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<crate::models::ScannerParamsLocationTreeLocation>>,
}

impl ScannerParamsLocationTree {
    /// Contains list of instruments for which scanner can be ran
    pub fn new() -> ScannerParamsLocationTree {
        ScannerParamsLocationTree {
            location: None,
        }
    }
}


