/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SummaryTotal {
    /// total change amount
    #[serde(rename = "chg", skip_serializing_if = "Option::is_none")]
    pub chg: Option<String>,
    /// change percent
    #[serde(rename = "rtn", skip_serializing_if = "Option::is_none")]
    pub rtn: Option<String>,
    /// set to true if any external account data is not available for starting or ending date, resulting in potentially unusual total values.
    #[serde(rename = "incompleteData", skip_serializing_if = "Option::is_none")]
    pub incomplete_data: Option<bool>,
    #[serde(rename = "endVal", skip_serializing_if = "Option::is_none")]
    pub end_val: Option<String>,
    #[serde(rename = "startVal", skip_serializing_if = "Option::is_none")]
    pub start_val: Option<String>,
}

impl SummaryTotal {
    pub fn new() -> SummaryTotal {
        SummaryTotal {
            chg: None,
            rtn: None,
            incomplete_data: None,
            end_val: None,
            start_val: None,
        }
    }
}


