/*
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SummaryBalanceByDate {
    #[serde(rename = "series", skip_serializing_if = "Option::is_none")]
    pub series: Option<Vec<crate::models::SummaryBalanceByDateSeries>>,
}

impl SummaryBalanceByDate {
    pub fn new() -> SummaryBalanceByDate {
        SummaryBalanceByDate {
            series: None,
        }
    }
}


